name: "Documentation Linter"

on:
  pull_request:
  push:
    branches:
      - "3.x"
      - "4.x"

jobs:
  documentation-linter:
    name: "Documentation Linter"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "MD Link Linter"
        uses: "docker://norberttech/md-link-linter:latest"
        with:
          entrypoint: "/composer/vendor/bin/mdlinklint"
          args: "--exclude=vendor --exclude=tests ."
